# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SF_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1387, 800)
        MainWindow.setStyleSheet("QTableView\n"
"{\n"
"    border-radius:2px;\n"
"    border: 2px solid rgb(109, 106, 247);         \n"
"    gridline-color:rgb(215, 234, 255);             \n"
"    background-color: rgb(201, 226, 239);\n"
"    alternate‎-background-color: rgb(201, 226, 239); \n"
"    selection-background-color: rgb(136, 200, 238);\n"
"}\n"
"QHeaderView::section\n"
"{\n"
"    background:qlineargradient(spread:pad, x1:0.505263, y1:0, x2:0.5, y2:1, stop:0 rgba(134, 244, 186, 255), stop:0.515789 rgba(137, 231, 209, 255), stop:1 rgba(141, 217, 233, 255));\n"
"    color: rgb(50, 67, 98);\n"
"    border-radius:2px;\n"
"    border: 1px solid rgb(215, 234, 255);\n"
"}\n"
"QCommandLinkButton\n"
"{\n"
"    color:rgb(0, 85, 255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 1)
        self.refresh = QtWidgets.QToolButton(self.centralwidget)
        self.refresh.setMinimumSize(QtCore.QSize(50, 50))
        self.refresh.setMaximumSize(QtCore.QSize(50, 50))
        self.refresh.setText("")
        self.refresh.setObjectName("refresh")
        self.gridLayout.addWidget(self.refresh, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 9, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 10, 1, 1)
        self.browser = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.browser.setMinimumSize(QtCore.QSize(200, 50))
        self.browser.setMaximumSize(QtCore.QSize(16777215, 12345678))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.browser.setFont(font)
        self.browser.setObjectName("browser")
        self.gridLayout.addWidget(self.browser, 0, 11, 1, 1)
        self.delete_2 = QtWidgets.QToolButton(self.centralwidget)
        self.delete_2.setMinimumSize(QtCore.QSize(50, 50))
        self.delete_2.setMaximumSize(QtCore.QSize(50, 50))
        self.delete_2.setText("")
        self.delete_2.setObjectName("delete_2")
        self.gridLayout.addWidget(self.delete_2, 0, 2, 1, 1)
        self.add = QtWidgets.QToolButton(self.centralwidget)
        self.add.setMinimumSize(QtCore.QSize(50, 50))
        self.add.setMaximumSize(QtCore.QSize(50, 50))
        self.add.setText("")
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 12, 1, 1)
        self.clear = QtWidgets.QToolButton(self.centralwidget)
        self.clear.setMinimumSize(QtCore.QSize(50, 50))
        self.clear.setMaximumSize(QtCore.QSize(50, 50))
        self.clear.setText("")
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 0, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 6, 1, 1)
        self.select_all = QtWidgets.QToolButton(self.centralwidget)
        self.select_all.setMinimumSize(QtCore.QSize(50, 50))
        self.select_all.setMaximumSize(QtCore.QSize(50, 50))
        self.select_all.setText("")
        self.select_all.setObjectName("select_all")
        self.gridLayout.addWidget(self.select_all, 0, 1, 1, 1)
        self.datatable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datatable.sizePolicy().hasHeightForWidth())
        self.datatable.setSizePolicy(sizePolicy)
        self.datatable.setLineWidth(0)
        self.datatable.setObjectName("datatable")
        self.datatable.setColumnCount(0)
        self.datatable.setRowCount(0)
        self.datatable.horizontalHeader().setMinimumSectionSize(40)
        self.datatable.verticalHeader().setDefaultSectionSize(40)
        self.gridLayout.addWidget(self.datatable, 1, 0, 1, 13)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1387, 26))
        self.menubar.setObjectName("menubar")
        self.set = QtWidgets.QMenu(self.menubar)
        self.set.setObjectName("set")
        self.account = QtWidgets.QMenu(self.set)
        self.account.setObjectName("account")
        self.theme = QtWidgets.QMenu(self.set)
        self.theme.setObjectName("theme")
        self.aboutbar = QtWidgets.QMenu(self.menubar)
        self.aboutbar.setObjectName("aboutbar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.destroy1 = QtWidgets.QAction(MainWindow)
        self.destroy1.setObjectName("destroy1")
        self.change = QtWidgets.QAction(MainWindow)
        self.change.setObjectName("change")
        self.password = QtWidgets.QAction(MainWindow)
        self.password.setObjectName("password")
        self.night = QtWidgets.QAction(MainWindow)
        self.night.setObjectName("night")
        self.day = QtWidgets.QAction(MainWindow)
        self.day.setObjectName("day")
        self.help = QtWidgets.QAction(MainWindow)
        self.help.setObjectName("help")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.account.addAction(self.destroy1)
        self.account.addAction(self.change)
        self.account.addAction(self.password)
        self.theme.addAction(self.night)
        self.theme.addAction(self.day)
        self.set.addAction(self.account.menuAction())
        self.set.addAction(self.theme.menuAction())
        self.set.addSeparator()
        self.aboutbar.addAction(self.help)
        self.aboutbar.addAction(self.about)
        self.menubar.addAction(self.set.menuAction())
        self.menubar.addAction(self.aboutbar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browser.setText(_translate("MainWindow", "🌏浏览器"))
        self.set.setTitle(_translate("MainWindow", "设置"))
        self.account.setTitle(_translate("MainWindow", "账户"))
        self.theme.setTitle(_translate("MainWindow", "主题"))
        self.aboutbar.setTitle(_translate("MainWindow", "关于"))
        self.destroy1.setText(_translate("MainWindow", "注销账号"))
        self.destroy1.setToolTip(_translate("MainWindow", "注销账号"))
        self.destroy1.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.change.setText(_translate("MainWindow", "切换账号"))
        self.change.setToolTip(_translate("MainWindow", "切换账号"))
        self.change.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.password.setText(_translate("MainWindow", "修改密码"))
        self.password.setToolTip(_translate("MainWindow", "修改密码"))
        self.password.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.night.setText(_translate("MainWindow", "夜间"))
        self.night.setToolTip(_translate("MainWindow", "夜间"))
        self.night.setShortcut(_translate("MainWindow", "Shift+N"))
        self.day.setText(_translate("MainWindow", "白昼"))
        self.day.setToolTip(_translate("MainWindow", "白昼"))
        self.day.setShortcut(_translate("MainWindow", "Shift+D"))
        self.help.setText(_translate("MainWindow", "帮助"))
        self.help.setToolTip(_translate("MainWindow", "帮助"))
        self.help.setShortcut(_translate("MainWindow", "Shift+H"))
        self.about.setText(_translate("MainWindow", "关于"))
        self.about.setToolTip(_translate("MainWindow", "关于"))
        self.about.setShortcut(_translate("MainWindow", "Shift+A"))
import picture.ui_resource_rc
