# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SF_Signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SF_Signup(object):
    def setupUi(self, SF_Signup):
        SF_Signup.setObjectName("SF_Signup")
        SF_Signup.resize(530, 380)
        SF_Signup.setMinimumSize(QtCore.QSize(530, 380))
        SF_Signup.setMaximumSize(QtCore.QSize(530, 380))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(9)
        SF_Signup.setFont(font)
        SF_Signup.setStyleSheet("QLabel#sign_up_now\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505263, y1:0, x2:0.5, y2:1, stop:0 rgba(150, 210, 250, 255), stop:0.831579 rgba(213, 248, 255, 255));\n"
"    color:rgb(255, 170, 255);\n"
"}\n"
"QLabel#error_tip\n"
"{\n"
"    font: 9pt \"等线\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
".QWidget\n"
"{\n"
"    background-color:rgb(253, 251, 242)\n"
"}\n"
"QPushButton#help\n"
"{\n"
"    \n"
"    background-color: rgb(253, 251, 242);\n"
"    border-radius:0px;\n"
"    font: 9pt \"等线\";\n"
"    color: rgb(150, 150, 150);\n"
"}\n"
"QPushButton#help:hover\n"
"{\n"
"    font: 9pt \"等线\";\n"
"    color: rgb(75, 75, 75);\n"
"}\n"
"QPushButton#help:pressed\n"
"{\n"
"    font: 9pt \"等线\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton#return_login\n"
"{\n"
"    border-image: url(:/tool_icon/tool/return_trigger.png);\n"
"}\n"
"QPushButton#return_login:hover\n"
"{\n"
"    border-image: url(:/tool_icon/tool/return_active.png);\n"
"}\n"
"QPushButton#return_login:pressed\n"
"{\n"
"    border-image: url(:/tool_icon/tool/return.png);\n"
"}\n"
"QPushButton#signup\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.505263, y1:0, x2:0.5, y2:1, stop:0.121053 rgba(184, 255, 236, 255), stop:0.852632 rgba(69, 249, 199, 255));\n"
"    border-radius:13px;\n"
"    font: 14pt \"华文仿宋\" bold;\n"
"    color: rgb(0, 0, 108)\n"
"}\n"
"QPushButton#signup:hover\n"
"{\n"
"    background-color:qlineargradient(spread:pad, x1:0.484, y1:1, x2:0.495, y2:0.023, stop:0.121053 rgba(142, 255, 225, 255), stop:0.852632 rgba(22, 249, 186, 255));\n"
"    font: 14pt \"华文仿宋\" bold;\n"
"    color: rgb(99, 0, 74);\n"
"    border:1px solid rgb(0, 170, 255)\n"
"}\n"
"QPushButton#signup:pressed\n"
"{\n"
"    background-color:rgb(75, 225, 255);\n"
"    border-radius:13px;\n"
"    font: 14pt \"华文仿宋\" bold;\n"
"    color: rgb(255, 255, 255);\n"
"    border:1px solid rgb(0, 170, 255)\n"
"}\n"
"QLineEdit\n"
"{\n"
"    font: 11pt \"宋体\";\n"
"    background-color: rgb(253, 251, 242);\n"
"    border:none;\n"
"    border-bottom:1px solid rgb(255, 230, 185);\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    border-bottom:1px solid rgb(255, 185, 71);\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    background-color: rgb(254, 254, 254);\n"
"    border-radius:7px;\n"
"    border:1px solid rgb(255, 85, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.sign_up_now = QtWidgets.QLabel(SF_Signup)
        self.sign_up_now.setGeometry(QtCore.QRect(0, 0, 530, 150))
        self.sign_up_now.setMinimumSize(QtCore.QSize(0, 150))
        self.sign_up_now.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(38)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.sign_up_now.setFont(font)
        self.sign_up_now.setAutoFillBackground(False)
        self.sign_up_now.setObjectName("sign_up_now")
        self.main = QtWidgets.QWidget(SF_Signup)
        self.main.setGeometry(QtCore.QRect(0, 139, 530, 241))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setItalic(False)
        self.main.setFont(font)
        self.main.setObjectName("main")
        self.return_login = QtWidgets.QPushButton(self.main)
        self.return_login.setGeometry(QtCore.QRect(7, 213, 25, 25))
        self.return_login.setMinimumSize(QtCore.QSize(25, 25))
        self.return_login.setMaximumSize(QtCore.QSize(25, 25))
        self.return_login.setText("")
        self.return_login.setObjectName("return_login")
        self.help = QtWidgets.QPushButton(self.main)
        self.help.setGeometry(QtCore.QRect(470, 210, 60, 30))
        self.help.setObjectName("help")
        self.signup = QtWidgets.QPushButton(self.main)
        self.signup.setGeometry(QtCore.QRect(135, 165, 240, 40))
        self.signup.setMinimumSize(QtCore.QSize(240, 40))
        self.signup.setMaximumSize(QtCore.QSize(240, 40))
        font = QtGui.QFont()
        font.setFamily("华文仿宋 13")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.signup.setFont(font)
        self.signup.setObjectName("signup")
        self.set_password = QtWidgets.QLineEdit(self.main)
        self.set_password.setGeometry(QtCore.QRect(135, 75, 240, 30))
        self.set_password.setMinimumSize(QtCore.QSize(240, 30))
        self.set_password.setMaximumSize(QtCore.QSize(240, 30))
        self.set_password.setText("")
        self.set_password.setMaxLength(20)
        self.set_password.setFrame(True)
        self.set_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.set_password.setObjectName("set_password")
        self.set_username = QtWidgets.QLineEdit(self.main)
        self.set_username.setEnabled(True)
        self.set_username.setGeometry(QtCore.QRect(135, 30, 240, 30))
        self.set_username.setMinimumSize(QtCore.QSize(240, 30))
        self.set_username.setMaximumSize(QtCore.QSize(240, 30))
        self.set_username.setText("")
        self.set_username.setMaxLength(20)
        self.set_username.setObjectName("set_username")
        self.password_again = QtWidgets.QLineEdit(self.main)
        self.password_again.setGeometry(QtCore.QRect(135, 120, 240, 30))
        self.password_again.setMinimumSize(QtCore.QSize(240, 30))
        self.password_again.setMaximumSize(QtCore.QSize(240, 30))
        self.password_again.setText("")
        self.password_again.setMaxLength(20)
        self.password_again.setFrame(True)
        self.password_again.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_again.setObjectName("password_again")
        self.error_tip = QtWidgets.QLabel(self.main)
        self.error_tip.setGeometry(QtCore.QRect(130, 210, 250, 20))
        self.error_tip.setText("")
        self.error_tip.setAlignment(QtCore.Qt.AlignCenter)
        self.error_tip.setObjectName("error_tip")
        self.loadin = QtWidgets.QLabel(self.main)
        self.loadin.setGeometry(QtCore.QRect(160, 170, 30, 30))
        self.loadin.setText("")
        self.loadin.setObjectName("loadin")
        self.main.raise_()
        self.sign_up_now.raise_()

        self.retranslateUi(SF_Signup)
        QtCore.QMetaObject.connectSlotsByName(SF_Signup)

    def retranslateUi(self, SF_Signup):
        _translate = QtCore.QCoreApplication.translate
        SF_Signup.setWindowTitle(_translate("SF_Signup", "Dialog"))
        self.sign_up_now.setText(_translate("SF_Signup", "     SIGN UP NOW"))
        self.return_login.setWhatsThis(_translate("SF_Signup", "<html><head/><body><p>返回登录</p></body></html>"))
        self.help.setWhatsThis(_translate("SF_Signup", "<html><head/><body><p>打开用户使用指南</p></body></html>"))
        self.help.setText(_translate("SF_Signup", "帮助"))
        self.signup.setText(_translate("SF_Signup", "注   册"))
        self.set_password.setPlaceholderText(_translate("SF_Signup", "设置密码（六位数以上）"))
        self.set_username.setPlaceholderText(_translate("SF_Signup", "设置账号（五位字符以上）"))
        self.password_again.setPlaceholderText(_translate("SF_Signup", "再次输入密码"))
import picture.ui_resource_rc
